(function(g){var window=this;var DDa=function(a,b){return g.Wb(a,b)},k6=function(a){g.cn(a,"zx",g.wb());
return a},l6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.fn(a.o,b,c)},EDa=function(a,b){var c=[];
g.Pk(b,function(a){try{var b=g.ED.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.DD(b)&&c.push(a):c.push(a)},a);
return c},FDa=function(a,b){var c=EDa(a,b);
(0,g.D)(c,function(a){g.ED.prototype.remove.call(this,a)},a)},GDa=function(a){if(a.Kd){if(a.Kd.locationOverrideToken)return{locationOverrideToken:a.Kd.locationOverrideToken};
if(null!=a.Kd.latitudeE7&&null!=a.Kd.longitudeE7)return{latitudeE7:a.Kd.latitudeE7,longitudeE7:a.Kd.longitudeE7}}return null},HDa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&g.Ym(e,d);return e},IDa=function(a){g.iG[a]&&(a=g.iG[a],(0,g.D)(a,function(a){g.gG[a]&&delete g.gG[a]}),a.length=0)},JDa=function(a){var b=g.fG();
if(b)if(b.clear(a),a)IDa(a);else for(var c in g.iG)IDa(c)},m6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Om;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",KDa(this,a.capabilities||""),LDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},KDa=function(a,b){a.capabilities.clear();
(0,g.Wd)(b.split(","),g.Da(DDa,MDa)).forEach(function(b){a.capabilities.add(b)})},LDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},n6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},o6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},NDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},ODa=function(a){return new n6(a)},PDa=function(a){return g.xa(a)?(0,g.I)(a,ODa):[]},p6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},q6=function(a){return g.xa(a)?"["+(0,g.I)(a,p6).join(",")+"]":"null"},r6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},QDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},s6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},t6=function(a,b){return g.Ja(a,function(a){return o6(a,b)})},RDa=function(){var a=(0,g.sH)();
a&&FDa(a,a.o.fe(!0))},u6=function(){var a=g.vH("yt-remote-connected-devices")||[];
g.fb(a);return a},SDa=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},TDa=function(a){g.uH("yt-remote-connected-devices",a,86400)},w6=function(){if(v6)return v6;
var a=g.vH("yt-remote-device-id");a||(a=r6(),g.uH("yt-remote-device-id",a,31536E3));for(var b=u6(),c=1,d=a;g.Na(b,d);)c++,d=a+"#"+c;return v6=d},x6=function(){var a=u6(),b=w6();
g.Na(a,b);g.xH()&&g.ib(a,b);a=SDa(a);if(g.Oa(a))try{g.RG("remote_sid")}catch(c){}else try{g.QG("remote_sid",a.join(","),-1)}catch(c){}},UDa=function(){return g.vH("yt-remote-session-browser-channel")},VDa=function(){return g.vH("yt-remote-local-screens")||[]},WDa=function(){g.uH("yt-remote-lounge-token-expiration",!0,86400)},XDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(VDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Bm)(c,function(a){return!g.Na(b,a)})&&WDa();
g.uH("yt-remote-local-screens",a,31536E3)},YDa=function(a,b){g.uH("yt-remote-session-browser-channel",a);
g.uH("yt-remote-session-screen-id",b);var c=u6(),d=w6();g.Na(c,d)||c.push(d);TDa(c);x6()},y6=function(a){a||(g.wH("yt-remote-session-screen-id"),g.wH("yt-remote-session-video-id"));
x6();a=u6();g.Ta(a,w6());TDa(a)},ZDa=function(){if(!z6){var a=g.PD();
a&&(z6=new g.yD(a))}return z6?!!z6.get("yt-remote-use-staging-server"):!1},$Da=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},aEa=function(a,b,c){c=void 0===c?null:c;
var d=g.Pd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.kd(d,g.ne("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},bEa=function(a){a=void 0===a?null:a;
var b=$Da(),c=window.document.getElementById(b),d=c&&g.rF(c,"loaded");d||c&&!d||(c=aEa(b,function(){g.rF(c,"loaded")||(g.qF(c,"loaded","true"),g.mG(b),g.qE(g.Da(JDa,b),0))},a))},cEa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):bEa(a)},A6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},dEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},B6=function(a){a.length?eEa(a.shift(),function(){B6(a)}):C6()},fEa=function(a){return"chrome-extension://"+a+D6},eEa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},E6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},C6=function(){var a=dEa();
a&&a(!1,"No cast extension found")},F6=function(){if(gEa){var a=2,b=dEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;eEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",C6,c)}},hEa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(F6(),a({command:"cast.sender.init"}))},iEa=function(){F6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);B6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+D6,"//www.gstatic.com/eureka/clank"+D6])},G6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Cd=b;this.D=(0,g.B)(this.QL,this);this.o=!1;this.A=0;this.B=this.Fa=null;this.C=[]},H6=function(){},I6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Z=new g.kn(this);this.A=new g.Cg;this.A.setInterval(250)},kEa=function(a,b,c){a.yk=1;
a.Ph=k6(b.clone());a.Ej=c;a.D=!0;jEa(a,null)},J6=function(a,b,c,d,e){a.yk=1;
a.Ph=k6(b.clone());a.Ej=null;a.D=c;e&&(a.PF=!1);jEa(a,d)},jEa=function(a,b){a.xl=(0,g.H)();
K6(a);a.ti=a.Ph.clone();l6(a.ti,"t",a.F);a.co=0;a.Xc=a.o.qt(a.o.Wn()?b:null);0<a.Zt&&(a.Yq=new g.ul((0,g.B)(a.iH,a,a.Xc),a.Zt));a.Z.X(a.Xc,"readystatechange",a.iX);var c=a.fj?g.dc(a.fj):{};a.Ej?(a.Sr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Xc.send(a.ti,a.Sr,a.Ej,c)):(a.Sr="GET",a.PF&&!g.Kd&&(c.Connection="close"),a.Xc.send(a.ti,a.Sr,null,c));a.o.Kf(1)},nEa=function(a,b,c){for(var d=!0;!a.Qi&&a.co<c.length;){var e=lEa(a,c);
if(e==L6){4==b&&(a.Qh=4,M6(15),d=!1);break}else if(e==mEa){a.Qh=4;M6(16);d=!1;break}else N6(a,e)}4==b&&0==c.length&&(a.Qh=1,M6(17),d=!1);a.Rf=a.Rf&&d;d||(O6(a),P6(a))},lEa=function(a,b){var c=a.co,d=b.indexOf("\n",c);
if(-1==d)return L6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return mEa;d+=1;if(d+c>b.length)return L6;var e=b.substr(d,c);a.co=d+c;return e},pEa=function(a,b){a.xl=(0,g.H)();
K6(a);var c=b?window.location.hostname:"";a.ti=a.Ph.clone();g.cn(a.ti,"DOMAIN",c);g.cn(a.ti,"t",a.F);try{a.Sf=new window.ActiveXObject("htmlfile")}catch(n){O6(a);a.Qh=7;M6(22);P6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in Q6)k=Q6[l];else if(l in oEa)k=Q6[l]=oEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=Q6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ld(g.Bc("b/12014412"),d+"</body></html>");a.Sf.open();a.Sf.write(g.bd(c));a.Sf.close();a.Sf.parentWindow.m=(0,g.B)(a.qW,a);a.Sf.parentWindow.d=(0,g.B)(a.YE,a,!0);a.Sf.parentWindow.rpcClose=(0,g.B)(a.YE,a,!1);c=a.Sf.createElement("DIV");a.Sf.parentWindow.document.body.appendChild(c);d=g.Pc(a.ti.toString());d=g.pb(g.Mc(d));d=g.ld(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.Kf(1)},
K6=function(a){a.Ox=(0,g.H)()+a.C;
qEa(a,a.C)},qEa=function(a,b){if(null!=a.Ol)throw Error("WatchDog timer not null");
a.Ol=R6((0,g.B)(a.HW,a),b)},S6=function(a){a.Ol&&(g.x.clearTimeout(a.Ol),a.Ol=null)},P6=function(a){a.o.aB()||a.Qi||a.o.Iq(a)},O6=function(a){S6(a);
g.mf(a.Yq);a.Yq=null;a.A.stop();g.qn(a.Z);if(a.Xc){var b=a.Xc;a.Xc=null;b.abort();b.dispose()}a.Sf&&(a.Sf=null)},N6=function(a,b){try{a.o.QE(a,b),a.o.Kf(4)}catch(c){}},sEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;rEa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){sEa(a,b,c,d,f)},f)})}},rEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{T6(d),c(!0)}catch(e){}};
d.onerror=function(){try{T6(d),c(!1)}catch(e){}};
d.onabort=function(){try{T6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{T6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},T6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},tEa=function(a){this.o=a;
this.A=new H6},uEa=function(a){var b=U6(a.o,a.Xl,"/mail/images/cleardot.gif");
k6(b);sEa(b.toString(),5E3,(0,g.B)(a.UK,a),3,2E3);a.Kf(1)},W6=function(a){var b=a.o.J;
if(null!=b)M6(5),b?(M6(11),V6(a.o,a,!1)):(M6(12),V6(a.o,a,!0));else if(a.Ke=new I6(a,void 0,void 0,void 0),a.Ke.fj=a.Xt,b=a.o,b=U6(b,b.Wn()?a.Om:null,a.Yt),M6(5),!g.Id||g.tc(10))l6(b,"TYPE","xmlhttp"),J6(a.Ke,b,!1,a.Om,!1);else{l6(b,"TYPE","html");var c=a.Ke;a=!!a.Om;c.yk=3;c.Ph=k6(b.clone());pEa(c,a)}},X6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new H6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},vEa=function(a,b){this.o=a;
this.map=b;this.context=null},wEa=function(a){g.pf.call(this,"statevent",a)},xEa=function(a,b){g.pf.call(this,"timingevent",a);
this.size=b},yEa=function(a){g.pf.call(this,"serverreachability",a)},BEa=function(a){zEa(a);
if(3==a.o){var b=a.In++,c=a.up.clone();g.cn(c,"SID",a.B);g.cn(c,"RID",b);g.cn(c,"TYPE","terminate");Y6(a,c);b=new I6(a,a.B,b,void 0);b.yk=2;b.Ph=k6(c.clone());(new window.Image).src=b.Ph;b.xl=(0,g.H)();K6(b)}AEa(a)},CEa=function(a){a.qL(1,0);
a.up=U6(a,null,a.Wt);Z6(a)},zEa=function(a){a.Eh&&(a.Eh.abort(),a.Eh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Lg&&(g.x.clearTimeout(a.Lg),a.Lg=null);$6(a);a.ke&&(a.ke.cancel(),a.ke=null);a.Kh&&(g.x.clearTimeout(a.Kh),a.Kh=null)},DEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new vEa(a.cS++,b));2!=a.o&&3!=a.o||Z6(a)},Z6=function(a){a.ke||a.Kh||(a.Kh=R6((0,g.B)(a.WE,a),0),a.mk=0)},FEa=function(a,b){if(1==a.o){if(!b){a.In=Math.floor(1E5*Math.random());
var c=a.In++,d=new I6(a,"",c,void 0);d.fj=null;var e=a7(a),f=a.up.clone();g.cn(f,"RID",c);g.cn(f,"CVER","1");Y6(a,f);kEa(d,f,e);a.ke=d;a.o=2}}else 3==a.o&&(b?EEa(a,b):0==a.A.length||a.ke||EEa(a))},EEa=function(a,b){if(b)if(6<a.Si){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.In-1;var d=a7(a)}else c=b.G,d=b.Ej;else c=a.In++,d=a7(a);var e=a.up.clone();g.cn(e,"SID",a.B);g.cn(e,"RID",c);g.cn(e,"AID",a.Ok);Y6(a,e);c=new I6(a,a.B,c,a.mk+1);c.fj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ke=c;kEa(c,e,d)},Y6=function(a,b){if(a.Bd){var c=a.Bd.GA();
c&&g.Ib(c,function(a,c){g.cn(b,c,a)})}},a7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Si&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Si?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},GEa=function(a){a.Bc||a.Lg||(a.G=1,a.Lg=R6((0,g.B)(a.VE,a),0),a.Zj=0)},b7=function(a){if(a.Bc||a.Lg||3<=a.Zj)return!1;
a.G++;a.Lg=R6((0,g.B)(a.VE,a),HEa(a,a.Zj));a.Zj++;return!0},V6=function(a,b,c){a.Qr=c;
a.ig=b.Zg;a.F||CEa(a)},$6=function(a){null!=a.Ti&&(g.x.clearTimeout(a.Ti),a.Ti=null)},HEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},c7=function(a,b){if(2==b||9==b){var c=null;
a.Bd&&(c=null);var d=(0,g.B)(a.VX,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),k6(c));rEa(c.toString(),1E4,d)}else M6(2);IEa(a,b)},IEa=function(a,b){a.o=0;
a.Bd&&a.Bd.Hz(b);AEa(a);zEa(a)},AEa=function(a){a.o=0;
a.ig=-1;if(a.Bd)if(0==a.C.length&&0==a.A.length)a.Bd.Rs();else{g.Wa(a.C);var b=g.Wa(a.A);a.C.length=0;a.A.length=0;a.Bd.Rs(b)}},U6=function(a,b,c){var d=g.dn(c);
if(""!=d.A)b&&g.Wm(d,b+"."+d.A),g.Xm(d,d.D);else{var e=window.location;d=HDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.wm&&g.Ib(a.wm,function(a,b){g.cn(d,b,a)});
g.cn(d,"VER",a.Si);Y6(a,d);return d},R6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},M6=function(a){d7.dispatchEvent(new wEa(d7,a))},JEa=function(){},KEa=function(a,b){this.action=a;
this.params=b||{}},e7=function(a,b){g.L.call(this);
this.o=new g.U(this.hW,0,this);g.M(this,this.o);this.Cd=5E3;this.A=0;if(g.za(a))b&&(a=(0,g.B)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},f7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.xD;this.A=new e7(this.EY,this);this.o=this.gb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.N=c||!1},LEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Qr,sessionId:a.o.B,arrayId:a.o.Ok}},MEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&FEa(a.o),BEa(a.o));a.H=0},g7=function(a){return!!a.o&&3==a.o.o},NEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},h7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Rg(a)||"";b&&(this.port=":"+b);this.domain=g.Qg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.A=!1))},i7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.$g(c+b,{})},j7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Da(a.C,d,!0),onError:g.Da(a.B,e),Gd:g.Da(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.HE(b,a)},REa=function(){var a=OEa;
PEa();k7.push(a);QEa(k7)},l7=function(a,b){PEa();
var c=k7,d=SEa(a,String(b));g.Oa(c)?TEa(d):(QEa(c),(0,g.D)(c,function(a){a(d)}))},PEa=function(){k7||(k7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",k7,void 0))},TEa=function(a){var b=(m7+1)%50;
m7=b;n7[b]=a;o7||(o7=49==b)},QEa=function(a){var b=n7;
if(b[0]){var c=m7,d=o7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
n7=Array(50);m7=-1;o7=!1}},SEa=function(a,b){var c=((0,g.H)()-UEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},p7=function(a){g.ZF.call(this);
this.G=a;this.o=[]},VEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},WEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Wd)(a.o,function(a){return!!s6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=VEa(a,b[d])||c;return c},XEa=function(a,b){var c=a.o.length;
a.o=(0,g.Wd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},q7=function(a,b,c,d){g.ZF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Fa=window.NaN},s7=function(a){p7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;r7(this);this.info("Initializing with "+q6(this.o))},YEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=i7(a.B,"/pairing/get_lounge_token_batch");
j7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.dM,a),(0,g.B)(a.cM,a))}},r7=function(a){var b=PDa(VDa());
b=(0,g.Wd)(b,function(a){return!a.uuid});
return WEa(a,b)},t7=function(a,b){XDa((0,g.I)(a.o,NDa));
b&&WDa()},v7=function(a,b){g.ZF.call(this);
this.F=b;var c=g.vH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Na(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;u7("Initialized with "+g.Ig(this.o))},ZEa=function(a,b,c){var d=i7(a.D,"/pairing/get_screen_availability");
j7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},w7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(u7("Updated online screens: "+g.Ig(a.o)),a.o=b,a.V("screenChange"));$Ea(a)},x7=function(a){(0,window.isNaN)(a.B)||g.sE(a.B);
a.B=g.qE((0,g.B)(a.Pw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},u7=function(a){l7("OnlineScreenService",a)},aFa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},$Ea=function(a){a=g.Rb(g.Jb(a.o,function(a){return a}));
g.fb(a);a.length?g.uH("yt-remote-online-screen-ids",a.join(","),60):g.wH("yt-remote-online-screen-ids")},y7=function(a){p7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};bFa(this)},dFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ee();if(k=(c?t6(k,c):null)||t6(k,b)){k.uuid=b;var l=z7(a,k);ZEa(a.A,l,function(a){e(a?l:null)})}else c?cFa(a,c,(0,g.B)(function(a){var f=z7(this,new n6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));ZEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},eFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},cFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.HE(i7(a.F,"/pairing/get_lounge_token_batch"),e)},fFa=function(a){a.o=a.B.Ee();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+q6(a.o))},bFa=function(a){A7(a);
a.B=new s7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.rM,a));fFa(a);a.C=PDa(g.vH("yt-remote-automatic-screen-cache")||[]);A7(a);a.info("Initializing automatic screens: "+q6(a.C));a.A=new v7(a.F,(0,g.B)(a.Ee,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},z7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=t6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.uH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,NDa)));A7(a);a.D[b.uuid]=b.id;g.uH("yt-remote-device-id-map",a.D,31536E3);return b},A7=function(a){a.D=g.vH("yt-remote-device-id-map")||{}},B7=function(a,b,c){g.ZF.call(this);
this.N=c;this.J=a;this.A=b;this.B=null},C7=function(a,b){l7(a.N,b)},D7=function(a,b){B7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.KY,this);this.D=(0,g.B)(this.TW,this);this.C=g.qE((0,g.B)(function(){gFa(this,null)},this),12E4)},hFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ig(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){C7(this,"Failed to send message: getMdxSessionStatus.")},a)):C7(a,"Sending yt message without session: "+g.Ig(b))},gFa=function(a,b){g.sE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Jq,a),d=(0,g.B)(a.Je,a);a.QA(b,c,d,5)}}else a.Je(Error("Waiting for session status timed out."))},E7=function(a,b,c){B7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.NY,this);this.o=g.A},iFa=function(a){a.o=a.J.pH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.Jq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Je(a)},a))},jFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}ZDa()&&(b.env_useStageMdx=1);return g.Yg(b)},F7=function(a,b){B7.call(this,a,b,"ManualSession");
this.o=g.qE((0,g.B)(this.Qk,this,null),150)},G7=function(a,b,c,d){g.ZF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.sV,this)},kFa=function(a,b){return b?g.Ja(a.B,function(a){return o6(b,a.label)},a):null},H7=function(a){l7("Controller",a)},OEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},I7=function(a){return a.D||!!a.B.length||!!a.o},J7=function(a,b,c){b!=a.o&&(g.mf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.TE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Qk(null)):a.V("yt-remote-cast2-session-change",null))},lFa=function(a){var b=a.A.oH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&o6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=kFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},rFa=function(a,b,c,d,e,f,k){mFa()?nFa(b,e,f,k)&&(L7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?oFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?oFa(a,c):(M7("Failed to load cast API: "+d),N7(!1),L7(!1),g.wH("yt-remote-cast-available"),g.wH("yt-remote-cast-receiver"),pFa(),
c(!1))},d?cEa():E6("CriOS")?hEa():E6("Android")&&E6("Chrome/")&&window.navigator.presentation?iEa():window.chrome&&window.navigator.presentation&&!E6("Edge")?(F6(),B6(qFa.map(fEa))):C6())):K7("Cannot initialize because not running Chrome")},pFa=function(){K7("dispose");
var a=O7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);sFa(!1);g.kG(P7);P7.length=0},Q7=function(){return!!g.vH("yt-remote-cast-installed")},tFa=function(){var a=g.vH("yt-remote-cast-receiver");
return a?a.friendlyName:null},uFa=function(){K7("clearCurrentReceiver");
g.wH("yt-remote-cast-receiver")},vFa=function(){return Q7()?O7()?O7().getCastSession():(M7("getCastSelector: Cast is not initialized."),null):(M7("getCastSelector: Cast API is not installed!"),null)},S7=function(){Q7()?O7()?R7()?(K7("Requesting cast selector."),O7().requestSession()):(K7("Wait for cast API to be ready to request the session."),P7.push(g.jG("yt-remote-cast2-api-ready",S7))):M7("requestCastSelector: Cast is not initialized."):M7("requestCastSelector: Cast API is not installed!")},T7=
function(a,b){R7()?O7().setConnectedScreenStatus(a,b):M7("setConnectedScreenStatus called before ready.")},mFa=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.LI||a},wFa=function(a,b){O7().init(a,b)},nFa=function(a,b,c,d){var e=!1;
O7()||(a=new G7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.uH("yt-remote-cast-available",a);g.nG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){K7("onReceiverSelected: "+a.friendlyName);
g.uH("yt-remote-cast-receiver",a);g.nG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){K7("onReceiverResumed: "+a.friendlyName);
g.uH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){K7("onSessionChange: "+p6(a));
a||g.wH("yt-remote-cast-receiver");g.nG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
K7("cloudview.createSingleton_: "+e);return e},O7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},oFa=function(a,b){N7(!0);
L7(!1);wFa(a,function(a){a?(sFa(!0),g.mG("yt-remote-cast2-api-ready")):(M7("Failed to initialize cast API."),N7(!1),g.wH("yt-remote-cast-available"),g.wH("yt-remote-cast-receiver"),pFa());b(a)})},K7=function(a){l7("cloudview",a)},M7=function(a){l7("cloudview",a)},N7=function(a){K7("setCastInstalled_ "+a);
g.uH("yt-remote-cast-installed",a)},R7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},sFa=function(a){K7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},L7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},U7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.mg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},V7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.mg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},W7=function(a){return a.sb()?((0,g.H)()-a.G)/1E3:0},X7=function(a,b){a.H=b;
a.G=(0,g.H)()},Y7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},Z7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&V7(a)},$7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.A);b.hasPrevious=a.mg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},b8=function(a,b){g.ZF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.OC;this.B=this.A=null;this.J=(0,g.B)(this.LS,this);this.G=(0,g.B)(this.Ln,this);this.H=(0,g.B)(this.KS,this);this.K=(0,g.B)(this.YS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Vx,this),xFa(this))):c=3;0!=c&&(b?this.Vx(c):g.qE((0,g.B)(function(){this.Vx(c)},this),0));
var d=vFa();d&&a8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},c8=function(a){return new U7(a.C.getPlayerContextData())},xFa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Da(this.nV,a),this))},a)},yFa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},d8=function(a,b){50>a.D.Cc()&&g.QC(a.D,b)},f8=function(a,b,c){var d=c8(a);
X7(d,c);-1E3!=d.o&&(d.o=b);e8(a,d)},g8=function(a,b,c){a.C.sendMessage(b,c)},e8=function(a,b){yFa(a);
a.C.setPlayerContextData($7(b));xFa(a)},a8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Ln(null));
a.B=b;a.B&&(l7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Ln(a.B.media[0]))},zFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=c8(a);b.contentId!=d.videoId&&l7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;X7(d,a.A.getEstimatedTime());e8(a,d)}else l7("CP","No cast media video. Ignoring state update.")},h8=function(a,b,c){return(0,g.B)(function(a){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),g8(this,b,c))},a)},i8=function(a,b,c){g.ZF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.N=window.NaN;this.W=[];this.C=this.G=this.B=this.ib=this.o=null;this.sa=a;this.W.push(g.IF(window,"beforeunload",(0,g.B)(this.UL,this)));this.A=[];this.ib=new U7;this.da=b.id;this.o=AFa(this,c);this.o.subscribe("handlerOpened",this.PS,this);this.o.subscribe("handlerClosed",this.MS,this);this.o.subscribe("handlerError",this.NS,this);this.o.subscribe("handlerMessage",this.OS,this);NEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.ib.videoId;g.xH()&&g.uH("yt-remote-session-video-id",a)},this)},j8=function(a){l7("conn",a)},AFa=function(a,b){return new f7(i7(a.sa,"/bc"),b)},k8=function(a,b){a.V("proxyStateChange",b)},BFa=function(a){a.D=g.qE((0,g.B)(function(){j8("Connecting timeout");
this.F(1)},a),2E4)},l8=function(a){g.sE(a.D);
a.D=window.NaN},m8=function(a){g.sE(a.N);
a.N=window.NaN},CFa=function(a){n8(a);
a.L=g.qE((0,g.B)(function(){o8(this,"getNowPlaying")},a),2E4)},n8=function(a){g.sE(a.L);
a.L=window.NaN},EFa=function(a,b){b&&(l8(a),m8(a));
b==(g7(a.o)&&(0,window.isNaN)(a.D))?b&&(k8(a,1),o8(a,"getSubtitlesTrack")):b?(a.aa()&&a.ib.reset(),k8(a,1),o8(a,"getNowPlaying"),DFa(a)):a.F(1)},FFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Zb(b.params)?a.ib.A=null:a.ib.A=b.params,a.V("remotePlayerChange"))},GFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;Z7(a.ib,c,d);a.V("remoteQueueChange")},IFa=function(a,b){b.params=b.params||{};
GFa(a,b);HFa(a,b);a.V("autoplayDismissed")},HFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
X7(a.ib,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.ib.o&&(c=-1E3);a.ib.o=c;c=Number(b.params.loadedTime);a.ib.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.ib.J=(0,window.isNaN)(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.ib.o?CFa(a):n8(a);
a.V("remotePlayerChange")},JFa=function(a,b){if(-1E3!=a.ib.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.o=c;c=(0,window.parseInt)(b.params.currentTime,10);X7(a.ib,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},KFa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=(0,window.parseInt)(b.params.volume,10);a.ib.muted=c;a.V("remotePlayerChange")},LFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},MFa=function(a,b){var c="true"==b.params.hasNext;
a.ib.mg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.V("previousNextChange")},DFa=function(a){g.sE(a.K);
a.K=g.qE((0,g.B)(a.F,a,1),864E5)},o8=function(a,b,c){c?j8("Sending: action="+b+", params="+g.Ig(c)):j8("Sending: action="+b);
a.o.sendMessage(b,c)},p8=function(a){p7.call(this,"ScreenServiceProxy");
this.ld=a;this.A=[];this.A.push(this.ld.$_s("screenChange",(0,g.B)(this.IY,this)));this.A.push(this.ld.$_s("onlineScreenChange",(0,g.B)(this.NU,this)))},RFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.jE("MDX_CONFIG")||b;RDa();x6();q8||(q8=new h7(b?b.loungeApiHost:void 0),ZDa()&&(q8.o="/api/loungedev"));r8||(r8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",r8,void 0));NFa();var c=s8();if(!c){var d=new y7(q8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=s8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);rFa(a,d,function(a){a?t8()&&T7(t8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.nG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),u8("Initializing: "+g.Ig(b)),v8.push(g.jG("yt-remote-cast2-availability-change",function(){g.nG("yt-remote-receiver-availability-change")})),v8.push(g.jG("yt-remote-cast2-receiver-selected",function(){w8(null);
g.nG("yt-remote-auto-connect","cast-selector-receiver")})),v8.push(g.jG("yt-remote-cast2-receiver-resumed",function(){g.nG("yt-remote-receiver-resumed","cast-selector-receiver")})),v8.push(g.jG("yt-remote-cast2-session-change",OFa)),v8.push(g.jG("yt-remote-connection-change",function(a){a?T7(t8(),"YouTube TV"):x8()||(T7(null,null),uFa())})),a=y8(),b.isAuto&&(a.id+="#dial"),g.nE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),u8(" -- with channel params: "+
g.Ig(a)),PFa(a),c.start(),t8()||QFa())},TFa=function(){var a=SFa();
Q7()&&g.vH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},SFa=function(){var a=s8().ld.$_gos();
var b=z8();b&&A8()&&(s6(a,b)||a.push(b));return QDa(a)},B8=function(){var a=UFa();
!a&&Q7()&&tFa()&&(a={key:"cast-selector-receiver",name:tFa()});return a},UFa=function(){var a=SFa(),b=z8();
b||(b=x8());return g.Ja(a,function(a){return b&&o6(b,a.key)?!0:!1})},z8=function(){var a=t8();
if(!a)return null;var b=s8().Ee();return t6(b,a)},OFa=function(a){u8("remote.onCastSessionChange_: "+p6(a));
if(a){var b=z8();b&&b.id==a.id?T7(b.id,"YouTube TV"):(b&&C8(),D8(a,1))}else A8()&&C8()},C8=function(){R7()?O7().stopSession():M7("stopSession called before API ready.");
var a=A8();a&&(a.disconnect(1),E8(null))},F8=function(){var a=A8();
return!!a&&3!=a.getProxyState()},u8=function(a){l7("remote",a)},s8=function(){if(!G8){var a=g.y("yt.mdx.remote.screenService_");
G8=a?new p8(a):null}return G8},t8=function(){return g.y("yt.mdx.remote.currentScreenId_")},VFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},WFa=function(){return g.y("yt.mdx.remote.connectData_")},w8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},A8=function(){return g.y("yt.mdx.remote.connection_")},E8=function(a){var b=A8();
w8(null);a||VFa("");g.ua("yt.mdx.remote.connection_",a,void 0);r8&&((0,g.D)(r8,function(b){b(a)}),r8.length=0);
b&&!a?g.nG("yt-remote-connection-change",!1):!b&&a&&g.nG("yt-remote-connection-change",!0)},x8=function(){var a=g.xH();
if(!a)return null;var b=s8().Ee();return t6(b,a)},D8=function(a,b){z8()&&z8();
VFa(a.id);var c=new i8(q8,a,y8());c.connect(b,WFa());c.subscribe("beforeDisconnect",function(a){g.nG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){A8()&&E8(null)});
E8(c)},QFa=function(){var a=x8();
a?(u8("Resume connection to: "+p6(a)),D8(a,0)):(y6(),uFa(),u8("Skipping connecting because no session screen found."))},NFa=function(){var a=y8();
if(g.Zb(a)){a=w6();var b=g.vH("yt-remote-session-name")||"",c=g.vH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},y8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},PFa=function(a){a?(g.uH("yt-remote-session-app",a.app),g.uH("yt-remote-session-name",a.name)):(g.wH("yt-remote-session-app"),g.wH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},H8=function(a,b,c){g.L.call(this);
this.C=a;this.T=b;this.A=new g.WF(this);g.M(this,this.A);this.A.R(b,"onCaptionsTrackListChanged",this.iU);this.A.R(b,"captionschanged",this.JS);this.A.R(b,"captionssettingschanged",this.xG);this.A.R(b,"videoplayerreset",this.Kq);this.A.R(b,"mdxautoplaycancel",this.TK);this.O=this.A.R(b,"onVolumeChange",this.zE);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.PE,this);c.subscribe("remotePlayerChange",this.Nn,this);c.subscribe("remoteQueueChange",this.Kq,this);c.subscribe("autoplayUpNext",this.lE,
this);c.subscribe("previousNextChange",this.ME,this);c.subscribe("nowAutoplaying",this.DE,this);c.subscribe("autoplayDismissed",this.kE,this);this.suggestion=null;this.H=new g.NP(64);this.B=new g.U(this.tG,500,this);g.M(this,this.B);this.D=new g.U(this.uG,1E3,this);g.M(this,this.D);this.K=new G6(this.jY,0,this);g.M(this,this.K);this.F={};this.L=new g.U(this.XG,1E3,this);g.M(this,this.L);this.J=new g.ul(this.NQ,1E3,this);g.M(this,this.J);this.N=g.A;this.xG();this.Kq();this.Nn()},I8=function(a,b){var c=
a.C,d=a.T.getVideoData().lengthSeconds;
c.J=b||0;c.player.V("progresssync",b,d)},XFa=function(a){I8(a,0);
a.B.stop();J8(a,new g.NP(64))},L8=function(a,b){if(K8(a)&&!a.G){var c=null;
b&&(c={style:a.T.xj()},g.gc(c,b));a.o.jG(a.T.getVideoData(1).videoId,c);a.F=c8(a.o).A}},M8=function(a,b){var c=a.T.ug();
if(c){var d=c.Ce();var e=c.listId.toString()}var f=a.T.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.Hk;f=GDa(f);var n=c8(c);l=l||0;var p={videoId:k,currentIndex:l};Z7(n,k,l);g.u(b)&&(X7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ig(f));g8(c,"setPlaylist",p);e||e8(c,n);J8(a,new g.NP(1))},YFa=function(a,b){if(b){var c=a.T.Gc("captions","tracklist",{KB:1});
c&&c.length?(a.T.Xd("captions","track",b),a.G=!1):(a.T.Yk("captions"),a.G=!0)}else a.T.Xd("captions","track",{})},K8=function(a){return c8(a.o).videoId==a.T.getVideoData(1).videoId},J8=function(a,b){a.D.stop();
var c=a.H;if(!g.TP(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.aU(a.T,d);a.H=b;ZFa(a.C,c,b)}},N8=function(a){g.V.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.nra()]},{I:"div",M:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.$U(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);$Fa(this,g.WT(a))},$Fa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Gc("remote","currentReceiver").name};
c=g.W(b,128)?g.SU("Error on $RECEIVER_NAME",c):b.sb()||g.W(b,4)?g.SU("Playing on $RECEIVER_NAME",c):g.SU("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},O8=function(a,b){g.yY.call(this,"Play on",0,a,b);
this.T=a;this.H={};this.R(a,"onMdxReceiversChange",this.K);this.R(a,"presentingplayerstatechange",this.K);this.K()},P8=function(a){g.BU.call(this,a);
this.A={key:r6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.NP(64);this.J=0;this.G=-1;if(!g.pN(g.X(this.player))){a=this.player;var b=g.mI(a);b&&(b=b.Cn())&&(b=new O8(a,b),g.M(this,b));b=new N8(a);g.M(this,b);g.pU(a,b.element,4)}},ZFa=function(a,b,c){a.F=c;
a.player.V("presentingplayerstatechange",new g.YP(c,b))},Q8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)C8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.ug();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.fb(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Hk,index:Math.max(a.player.PC(),0),currentTime:0==f?void 0:f};(d=GDa(d))&&(c.locationInfo=d);d=c}else d=null;u8("Connecting to: "+g.Ig(b));"cast-selector-receiver"==b.key?(w8(d||null),R7()?O7().setLaunchParams(d||
null):M7("setLaunchParams called before ready.")):!d&&F8()&&t8()==b.key?g.nG("yt-remote-connection-change",!0):(C8(),w8(d||null),d=s8().Ee(),(d=t6(d,b.key))&&D8(d,1))}},oEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},Q6={"'":"\\'"},aGa={},MDa={XZ:"atp",H4:"ska",W3:"que",h3:"mus",D4:"sus",k1:"dsp"};
m6.prototype.Yo=function(){var a=new m6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var z6,v6="",D6=A6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",gEa=A6("loadCastFramework")||A6("loadCastApplicationFramework"),qFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(G6,g.L);g.h=G6.prototype;g.h.PL=function(a){this.C=arguments;this.o=!1;this.Fa?this.B=(0,g.H)()+this.Cd:this.Fa=g.Dg(this.D,this.Cd)};
g.h.stop=function(){this.Fa&&(g.Eg(this.Fa),this.Fa=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.Y=function(){this.stop();G6.fa.Y.call(this)};
g.h.QL=function(){this.B?(this.Fa=g.Dg(this.D,this.B-(0,g.H)()),this.B=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};H6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
H6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=I6.prototype;g.h.fj=null;g.h.Rf=!1;g.h.Ol=null;g.h.Ox=null;g.h.xl=null;g.h.yk=null;g.h.Ph=null;g.h.ti=null;g.h.Ej=null;g.h.Xc=null;g.h.co=0;g.h.Sf=null;g.h.Sr=null;g.h.Qh=null;g.h.Pm=-1;g.h.PF=!0;g.h.Qi=!1;g.h.Zt=0;g.h.Yq=null;var mEa={},L6={};g.h=I6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.iX=function(a){a=a.target;var b=this.Yq;b&&3==g.Jx(a)?b.Lm():this.iH(a)};
g.h.iH=function(a){try{if(a==this.Xc)a:{var b=g.Jx(this.Xc),c=this.Xc.A,d=this.Xc.getStatus();if(g.Id&&!g.tc(10)||g.Kd&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.rf&&!g.Nx(this.Xc))break a;this.Qi||4!=b||7==c||(8==c||0>=d?this.o.Kf(3):this.o.Kf(2));S6(this);var e=this.Xc.getStatus();this.Pm=e;var f=g.Nx(this.Xc);(this.Rf=200==e)?(4==b&&O6(this),this.D?(nEa(this,b,f),g.rf&&this.Rf&&3==b&&(this.Z.X(this.A,"tick",this.eX),this.A.start())):N6(this,f),this.Rf&&!this.Qi&&(4==b?this.o.Iq(this):
(this.Rf=!1,K6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Qh=3,M6(13)):(this.Qh=0,M6(14)),O6(this),P6(this))}}catch(k){this.Xc&&g.Nx(this.Xc)}finally{}};
g.h.eX=function(){var a=g.Jx(this.Xc),b=g.Nx(this.Xc);this.co<b.length&&(S6(this),nEa(this,a,b),this.Rf&&4!=a&&K6(this))};
g.h.qW=function(a){R6((0,g.B)(this.pW,this,a),0)};
g.h.pW=function(a){this.Qi||(S6(this),N6(this,a),K6(this))};
g.h.YE=function(a){R6((0,g.B)(this.oW,this,a),0)};
g.h.oW=function(a){this.Qi||(O6(this),this.Rf=a,this.o.Iq(this),this.o.Kf(4))};
g.h.cancel=function(){this.Qi=!0;O6(this)};
g.h.HW=function(){this.Ol=null;var a=(0,g.H)();0<=a-this.Ox?(2!=this.yk&&this.o.Kf(3),O6(this),this.Qh=2,M6(18),P6(this)):qEa(this,this.Ox-a)};g.h=tEa.prototype;g.h.Xt=null;g.h.Ke=null;g.h.Zq=!1;g.h.bB=null;g.h.pp=null;g.h.Su=null;g.h.Yt=null;g.h.ff=null;g.h.Zg=-1;g.h.Om=null;g.h.Xl=null;g.h.connect=function(a){this.Yt=a;a=U6(this.o,null,this.Yt);M6(3);this.bB=(0,g.H)();var b=this.o.H;null!=b?(this.Om=b[0],(this.Xl=b[1])?(this.ff=1,uEa(this)):(this.ff=2,W6(this))):(l6(a,"MODE","init"),this.Ke=new I6(this,void 0,void 0,void 0),this.Ke.fj=this.Xt,J6(this.Ke,a,!1,null,!0),this.ff=0)};
g.h.UK=function(a){if(a)this.ff=2,W6(this);else{M6(4);var b=this.o;b.ig=b.Eh.Zg;c7(b,9)}a&&this.Kf(2)};
g.h.qt=function(a){return this.o.qt(a)};
g.h.abort=function(){this.Ke&&(this.Ke.cancel(),this.Ke=null);this.Zg=-1};
g.h.aB=function(){return!1};
g.h.QE=function(a,b){this.Zg=a.Pm;if(0==this.ff)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.ig=this.Zg;c7(c,2);return}this.Om=c[0];this.Xl=c[1]}else c=this.o,c.ig=this.Zg,c7(c,2);else if(2==this.ff)if(this.Zq)M6(7),this.Su=(0,g.H)();else if("11111"==b){if(M6(6),this.Zq=!0,this.pp=(0,g.H)(),c=this.pp-this.bB,!g.Id||g.tc(10)||500>c)this.Zg=200,this.Ke.cancel(),M6(12),V6(this.o,this,!0)}else M6(8),this.pp=this.Su=(0,g.H)(),this.Zq=!1};
g.h.Iq=function(){this.Zg=this.Ke.Pm;if(this.Ke.Rf)0==this.ff?this.Xl?(this.ff=1,uEa(this)):(this.ff=2,W6(this)):2==this.ff&&((!g.Id||g.tc(10)?!this.Zq:200>this.Su-this.pp)?(M6(11),V6(this.o,this,!1)):(M6(12),V6(this.o,this,!0)));else{0==this.ff?M6(9):2==this.ff&&M6(10);var a=this.o;a.ig=this.Zg;c7(a,2)}};
g.h.Wn=function(){return this.o.Wn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Kf=function(a){this.o.Kf(a)};g.h=X6.prototype;g.h.wm=null;g.h.ke=null;g.h.Bc=null;g.h.Wt=null;g.h.up=null;g.h.xz=null;g.h.Hp=null;g.h.In=0;g.h.cS=0;g.h.Bd=null;g.h.Kh=null;g.h.Lg=null;g.h.Ti=null;g.h.Eh=null;g.h.Qr=null;g.h.Ok=-1;g.h.YB=-1;g.h.ig=-1;g.h.mk=0;g.h.Zj=0;g.h.Si=8;var d7=new g.Qf;g.C(wEa,g.pf);g.C(xEa,g.pf);g.C(yEa,g.pf);g.h=X6.prototype;g.h.connect=function(a,b,c,d,e){M6(0);this.Wt=b;this.wm=c||{};d&&g.u(e)&&(this.wm.OSID=d,this.wm.OAID=e);this.F?(R6((0,g.B)(this.Rz,this,a),100),CEa(this)):this.Rz(a)};
g.h.Rz=function(a){this.Eh=new tEa(this);this.Eh.Xt=null;this.Eh.A=this.D;this.Eh.connect(a)};
g.h.aB=function(){return 0==this.o};
g.h.WE=function(a){this.Kh=null;FEa(this,a)};
g.h.VE=function(){this.Lg=null;this.Bc=new I6(this,this.B,"rpc",this.G);this.Bc.fj=null;this.Bc.Zt=0;var a=this.xz.clone();g.cn(a,"RID","rpc");g.cn(a,"SID",this.B);g.cn(a,"CI",this.Qr?"0":"1");g.cn(a,"AID",this.Ok);Y6(this,a);if(!g.Id||g.tc(10))g.cn(a,"TYPE","xmlhttp"),J6(this.Bc,a,!0,this.Hp,!1);else{g.cn(a,"TYPE","html");var b=this.Bc,c=!!this.Hp;b.yk=3;b.Ph=k6(a.clone());pEa(b,c)}};
g.h.QE=function(a,b){if(0!=this.o&&(this.Bc==a||this.ke==a))if(this.ig=a.Pm,this.ke==a&&3==this.o)if(7<this.Si){try{var c=this.D.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.Lg){if(this.Bc)if(this.Bc.xl+3E3<this.ke.xl)$6(this),this.Bc.cancel(),this.Bc=null;else break a;b7(this);M6(19)}}else this.YB=c[1],0<this.YB-this.Ok&&37500>c[2]&&this.Qr&&0==this.Zj&&!this.Ti&&(this.Ti=R6((0,g.B)(this.ES,this),6E3));else c7(this,11)}else b!=aGa.a0.o&&c7(this,11);else if(this.Bc==a&&
$6(this),!g.F(b)){c=this.D.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ok=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Hp=e[2],e=e[3],null!=e?this.Si=e:this.Si=6,this.o=3,this.Bd&&this.Bd.Jz(),this.xz=U6(this,this.Wn()?this.Hp:null,this.Wt),GEa(this)):"stop"==e[0]&&c7(this,7):3==this.o&&("stop"==e[0]?c7(this,7):"noop"!=e[0]&&this.Bd&&this.Bd.Iz(e),this.Zj=0)}}};
g.h.ES=function(){null!=this.Ti&&(this.Ti=null,this.Bc.cancel(),this.Bc=null,b7(this),M6(20))};
g.h.Iq=function(a){if(this.Bc==a){$6(this);this.Bc=null;var b=2}else if(this.ke==a)this.ke=null,b=1;else return;this.ig=a.Pm;if(0!=this.o)if(a.Rf)1==b?(b=(0,g.H)()-a.xl,d7.dispatchEvent(new xEa(d7,a.Ej?a.Ej.length:0,b,this.mk)),Z6(this),this.C.length=0):GEa(this);else{var c=a.Qh,d;if(!(d=3==c||7==c||0==c&&0<this.ig)){if(d=1==b)this.ke||this.Kh||1==this.o||2<=this.mk?d=!1:(this.Kh=R6((0,g.B)(this.WE,this,a),HEa(this,this.mk)),this.mk++,d=!0);d=!(d||2==b&&b7(this))}if(d)switch(c){case 1:c7(this,5);
break;case 4:c7(this,10);break;case 3:c7(this,6);break;case 7:c7(this,12);break;default:c7(this,2)}}};
g.h.qL=function(a){if(!g.Na(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.VX=function(a){a?M6(2):(M6(1),IEa(this,8))};
g.h.qt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Dx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Bd&&this.Bd.isActive(this)};
g.h.Kf=function(a){d7.dispatchEvent(new yEa(d7,a))};
g.h.Wn=function(){return!(!g.Id||g.tc(10))};
g.h=JEa.prototype;g.h.Jz=function(){};
g.h.Iz=function(){};
g.h.Hz=function(){};
g.h.Rs=function(){};
g.h.GA=function(){return{}};
g.h.isActive=function(){return!0};g.C(e7,g.L);g.h=e7.prototype;g.h.hW=function(){this.Cd=Math.min(3E5,2*this.Cd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Cd+15E3*Math.random();g.Cu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Cd=5E3};g.C(f7,JEa);g.h=f7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.ce=function(a){return this.B.ce(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.mf(this.B),MEa(this),g.mf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new X6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Bd=null);d.Bd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Ok):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):g7(this)&&DEa(this.o,c)};
g.h.Jz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)DEa(this.o,a[b])}this.V("handlerOpened")};
g.h.Hz=function(a){var b=2==a&&401==this.o.ig;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Rs=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.GA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.gc(a,this.D);return a};
g.h.Iz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),BEa(this.o)):this.V("handlerMessage",new KEa(a[0],a[1]))};
g.h.EY=function(){this.A.isActive();var a=this.o,b=0;a.Bc&&b++;a.ke&&b++;0!=b||this.connect(this.D,this.C)};h7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
h7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
h7.prototype.D=function(a){a(Error("request timed out"))};var UEa=(0,g.H)(),k7=null,n7=Array(50),m7=-1,o7=!1;g.C(p7,g.ZF);p7.prototype.Ee=function(){return this.o};
p7.prototype.contains=function(a){return!!s6(this.o,a)};
p7.prototype.get=function(a){return a?t6(this.o,a):null};
p7.prototype.info=function(a){l7(this.G,a)};g.C(q7,g.ZF);var bGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=q7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Fa)&&this.nH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Fa)||(g.sE(this.Fa),this.Fa=window.NaN)};
g.h.Y=function(){this.stop();q7.fa.Y.call(this)};
g.h.nH=function(){this.Fa=window.NaN;this.o=g.HE(i7(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.GY,this),onError:(0,g.B)(this.FY,this),Gd:(0,g.B)(this.HY,this)})};
g.h.GY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new n6(c))};
g.h.FY=function(a){this.o=null;a.status&&404==a.status?this.A>=bGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=bGa[this.A],this.Fa=g.qE((0,g.B)(this.nH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.HY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(s7,p7);g.h=s7.prototype;g.h.start=function(){r7(this)&&this.V("screenChange");!g.vH("yt-remote-lounge-token-expiration")&&YEa(this);g.sE(this.A);this.A=g.qE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){r7(this);VEa(this,a);t7(this,!1);this.V("screenChange");b(a);a.token||YEa(this)};
g.h.remove=function(a,b){var c=r7(this);XEa(this,a)&&(t7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Lr=function(a,b,c,d){var e=r7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,t7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.Y=function(){g.sE(this.A);s7.fa.Y.call(this)};
g.h.dM=function(a){r7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}t7(this,!b);b&&l7(this.G,"Missed "+b+" lounge tokens.")};
g.h.cM=function(a){l7(this.G,"Requesting lounge tokens failed: "+a)};g.C(v7,g.ZF);g.h=v7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.vH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?x7(this):(this.C=(0,g.H)()+3E5,g.uH("yt-remote-fast-check-period",this.C),this.Pw())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){u7("Updating availability on schedule.");var a=this.F(),b=g.Jb(this.o,function(b,d){return b&&!!t6(a,d)},this);
w7(this,b)};
g.h.Y=function(){g.sE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);v7.fa.Y.call(this)};
g.h.Pw=function(){g.sE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=aFa(this);if(g.Ob(a)){var b=i7(this.D,"/pairing/get_screen_availability");this.A=j7(this.D,b,{lounge_token:g.Rb(a).join(",")},(0,g.B)(this.PV,this,a),(0,g.B)(this.OV,this))}else w7(this,{}),x7(this)};
g.h.PV=function(a,b){this.A=null;var c=g.Rb(aFa(this));if(g.gb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;w7(this,d);x7(this)}else this.sc("Changing Screen set during request."),this.Pw()};
g.h.OV=function(a){this.sc("Screen availability failed: "+a);this.A=null;x7(this)};
g.h.sc=function(a){l7("OnlineScreenService",a)};g.C(y7,p7);g.h=y7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Lr=function(a,b,c,d){this.B.contains(a)?this.B.Lr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,l7(this.G,a),d(Error(a)))};
g.h.Ee=function(a){return a?this.o:g.Va(this.o,(0,g.Wd)(this.C,function(a){return!this.contains(a)},this))};
g.h.oH=function(){return(0,g.Wd)(this.Ee(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.pH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new q7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.mf(f);d(z7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.mf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.JY=function(a,b,c,d){g.HE(i7(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new n6(d.screen||{});if(!e.name||eFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);eFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(z7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Gd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.mf(this.B);g.mf(this.A);y7.fa.Y.call(this)};
g.h.rM=function(){fFa(this);this.V("screenChange");this.A.update()};
y7.prototype.dispose=y7.prototype.dispose;g.C(B7,g.ZF);g.h=B7.prototype;g.h.Jq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Je=function(a){this.la()||(a&&C7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){l7(this.N,a)};
g.h.rH=function(){return null};
g.h.Xw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){C7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Xw("");B7.fa.Y.call(this)};g.C(D7,B7);g.h=D7.prototype;g.h.Ww=function(a){if(this.o){if(this.o==a)return;C7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);hFa(this)};
g.h.Qk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ig(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Je()},this),(0,g.B)(function(){this.Je(Error("Failed to stop receiver app."))},this)):this.Je(Error("Stopping cast device witout session."))};
g.h.Xw=g.A;g.h.Y=function(){this.info("disposeInternal");g.sE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;D7.fa.Y.call(this)};
g.h.TW=function(a,b){if(!this.la())if(b){var c=g.xx(b);if(g.Aa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ig(c));switch(d){case "mdxSessionStatus":gFa(this,c.screenId);break;default:C7(this,"Unknown youtube message: "+d)}}else C7(this,"Unable to parse message.")}else C7(this,"No data in message.")};
g.h.QA=function(a,b,c,d){dFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(C7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.qE((0,g.B)(this.QA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.rH=function(){return this.o};
g.h.KY=function(a){this.la()||a||(C7(this,"Cast session died."),this.Je())};g.C(E7,B7);g.h=E7.prototype;g.h.Ww=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Qk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.sE(this.F);this.C?this.C.stop((0,g.B)(this.Je,this,null),(0,g.B)(this.Je,this,"Failed to stop DIAL device.")):this.Je()};
g.h.Y=function(){this.o();this.o=g.A;g.sE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;E7.fa.Y.call(this)};
g.h.NY=function(a){this.la()||a||(C7(this,"DIAL session died."),this.o(),this.o=g.A,this.Je())};
g.h.Du=function(a){this.K=r6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,jFa(this));a(b);iFa(this)}else this.G=(0,g.B)(function(){g.sE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,jFa(this));a(b);iFa(this)},this),this.F=g.qE((0,g.B)(function(){this.G()},this),100)};
g.h.GN=function(a,b,c){dFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Jq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Du(b,c)},this),(0,g.B)(function(a){C7(this,"Failed to get DIAL screen: "+a);
this.Du(b,c)},this))};g.C(F7,B7);F7.prototype.stop=function(){this.Je()};
F7.prototype.Ww=g.A;F7.prototype.Qk=function(){g.sE(this.o);this.o=window.NaN;var a=t6(this.J.Ee(),this.A.label);a?this.Jq(a):this.Je(Error("No such screen"))};
F7.prototype.Y=function(){g.sE(this.o);this.o=window.NaN;F7.fa.Y.call(this)};g.C(G7,g.ZF);g.h=G7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.SE,this),(0,g.B)(this.wV,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.pT,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),REa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.qH,this)),this.B=lFa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)),this.V("yt-remote-cast2-availability-change",I7(this)),b(!0))},this),(0,g.B)(function(a){this.sc("Failed to initialize API: "+g.Ig(a));
b(!1)},this))};
g.h.DX=function(a,b){H7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)H7("Unsetting old screen status: "+this.o.A.friendlyName),J7(this,null)}if(a&&b){if(!this.o){c=t6(this.A.Ee(),a);if(!c){H7("setConnectedScreenStatus: Unknown screen.");return}var d=kFa(this,c);d||(H7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.sc("Failed to set initial custom receivers: "+g.Ig(a))},this)));
H7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);J7(this,new F7(this.A,d),!0)}this.o.Xw(b)}else H7("setConnectedScreenStatus: no screen.")};
g.h.EX=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.Qk(a):this.sc("Setting connection data without a session")};
g.h.MY=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),J7(this,null)):H7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.SE,this),(0,g.B)(this.TV,this))};
g.h.Y=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.qH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],OEa);g.mf(this.o);G7.fa.Y.call(this)};
g.h.sc=function(a){l7("Controller",a)};
g.h.TE=function(a,b){this.o==a&&(b||J7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.sV=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),H7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)H7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{H7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:J7(this,
new F7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:J7(this,new E7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:J7(this,new D7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.pT=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return H7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);J7(this,new E7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.GN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Du,b))};
g.h.SE=function(a){if(!this.la()){H7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)H7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),J7(this,new D7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=t6(this.A.Ee(),c.label);
d&&o6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(H7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.mf(this.o),this.o=new D7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.TE,this,this.o)),this.o.Qk(null));this.o.Ww(a)}}};
g.h.LY=function(){return this.o?this.o.rH():null};
g.h.TV=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.Ig(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&J7(this,null))};
g.h.wV=function(a){H7("Receiver availability updated: "+a);if(!this.la()){var b=I7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;I7(this)!=b&&this.V("yt-remote-cast2-availability-change",I7(this))}};
g.h.qH=function(){this.la()||(this.B=lFa(this),H7("Updating custom receivers: "+g.Ig(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.sc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",I7(this)))};
G7.prototype.setLaunchParams=G7.prototype.EX;G7.prototype.setConnectedScreenStatus=G7.prototype.DX;G7.prototype.stopSession=G7.prototype.MY;G7.prototype.getCastSession=G7.prototype.LY;G7.prototype.requestSession=G7.prototype.requestSession;G7.prototype.init=G7.prototype.init;G7.prototype.dispose=G7.prototype.dispose;var P7=[];g.h=U7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";V7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.mg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.sb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+W7(this):this.J};
g.h.clone=function(){return new U7($7(this))};g.C(b8,g.ZF);g.h=b8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,h8(this,"play")):g8(this,"play"),f8(this,1,Y7(c8(this))),this.V("remotePlayerChange")):d8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,h8(this,"pause")):g8(this,"pause"),f8(this,2,Y7(c8(this))),this.V("remotePlayerChange")):d8(this,this.pause)};
g.h.mH=function(a){if(1==this.o){if(this.A){var b=c8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.sb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,h8(this,"seekTo",{newTime:a}))}else g8(this,"seekTo",{newTime:a});f8(this,3,a);this.V("remotePlayerChange")}else d8(this,g.Da(this.mH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,h8(this,"stopVideo")):g8(this,"stopVideo");var a=c8(this);a.index=-1;a.videoId="";V7(a);e8(this,a);this.V("remotePlayerChange")}else d8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=c8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){l7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){l7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);g8(this,"setVolume",e)}c.muted=b;c.volume=a;e8(this,c)}else d8(this,g.Da(this.setVolume,a,b))};
g.h.jG=function(a,b){if(1==this.o){var c=c8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ig(b.style),g.gc(d,c.A));g8(this,"setSubtitlesTrack",d);e8(this,c)}else d8(this,g.Da(this.jG,a,b))};
g.h.Ux=function(a,b){if(1==this.o){g8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Mb.id});var c=c8(this);c.audioTrackId=b.Mb.id;e8(this,c)}else d8(this,g.Da(this.Ux,a,b))};
g.h.lH=function(a,b){if(1==this.o){if(a&&b){var c=c8(this);Z7(c,a,b);e8(this,c)}g8(this,"previous")}else d8(this,g.Da(this.lH,a,b))};
g.h.kH=function(a,b){if(1==this.o){if(a&&b){var c=c8(this);Z7(c,a,b);e8(this,c)}g8(this,"next")}else d8(this,g.Da(this.kH,a,b))};
g.h.kA=function(){1==this.o?g8(this,"dismissAutoplay"):d8(this,this.kA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}b8.fa.dispose.call(this)};
g.h.Y=function(){yFa(this);this.C=null;this.D.clear();a8(this,null);b8.fa.Y.call(this)};
g.h.Vx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.RC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.nV=function(a,b){this.V(a,b)};
g.h.LS=function(a){if(!a)this.Ln(null),a8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=c8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)l7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,e8(this,b)}};
g.h.Ln=function(a){l7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),zFa(this),this.V("remotePlayerChange")};
g.h.KS=function(a){a?(zFa(this),this.V("remotePlayerChange")):this.Ln(null)};
g.h.YS=function(){var a=vFa();a&&a8(this,a)};
g.h.sc=function(a){l7("CP",a)};g.C(i8,g.ZF);g.h=i8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=k||0;this.ib.state=3;X7(this.ib,m);this.C="UNSUPPORTED";j8("Connecting with setPlaylist and params: "+g.Ig(l));this.o.connect({method:"setPlaylist",
params:g.Ig(l)},a,UDa())}else j8("Connecting without params"),this.o.connect({},a,UDa());BFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),k8(this,3));i8.fa.dispose.call(this)};
g.h.Y=function(){l8(this);n8(this);m8(this);g.sE(this.J);this.J=window.NaN;g.sE(this.K);this.K=window.NaN;this.B=null;g.JF(this.W);this.W.length=0;this.o.dispose();i8.fa.Y.call(this);this.C=this.G=this.A=this.ib=this.o=null};
g.h.UL=function(){this.F(2)};
g.h.PS=function(){j8("Channel opened");this.O&&(this.O=!1,m8(this),this.N=g.qE((0,g.B)(function(){j8("Timing out waiting for a screen.");this.F(1)},this),15E3));
YDa(LEa(this.o),this.da)};
g.h.MS=function(){j8("Channel closed");(0,window.isNaN)(this.D)?y6(!0):y6();this.dispose()};
g.h.NS=function(a){y6();(0,window.isNaN)(this.H())?(j8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,j8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),k8(this,2))};
g.h.OS=function(a){a.params?j8("Received: action="+a.action+", params="+g.Ig(a.params)):j8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.xx(a.params.devices);this.A=(0,g.I)(a,function(a){return new m6(a)});
a=!!g.Ja(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
EFa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
EFa(this,!1);break;case "remoteConnected":var b=new m6(g.xx(a.params.device));g.Ja(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new m6(g.xx(a.params.device));g.Ua(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":GFa(this,a);break;case "nowPlaying":IFa(this,a);break;case "onStateChange":HFa(this,a);break;case "onAdStateChange":JFa(this,a);break;case "onVolumeChanged":KFa(this,a);break;case "onSubtitlesTrackChanged":FFa(this,a);break;case "nowAutoplaying":LFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":MFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:j8("Unrecognized action: "+a.action)}};
g.h.qX=function(){if(this.B){var a=this.B;this.B=null;this.ib.videoId!=a&&o8(this,"getNowPlaying")}};
i8.prototype.subscribe=i8.prototype.subscribe;i8.prototype.unsubscribeByKey=i8.prototype.ce;i8.prototype.ia=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?g7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
i8.prototype.getProxyState=i8.prototype.ia;i8.prototype.F=function(a){j8("Disconnecting with "+a);l8(this);this.V("beforeDisconnect",a);1==a&&y6();MEa(this.o,a);this.dispose()};
i8.prototype.disconnect=i8.prototype.F;i8.prototype.ha=function(){var a=this.ib;this.B&&(a=this.ib.clone(),Z7(a,this.B,a.index));return $7(a)};
i8.prototype.getPlayerContextData=i8.prototype.ha;
i8.prototype.pa=function(a){var b=new U7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.B=b.videoId,g.sE(this.J),this.J=g.qE((0,g.B)(this.qX,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.o==b.o&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&Y7(this.ib)==Y7(b)&&g.Ig(this.ib.A)==g.Ig(b.A)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
i8.prototype.setPlayerContextData=i8.prototype.pa;i8.prototype.aa=function(){var a=this.o.F.id,b=g.Ja(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
i8.prototype.getOtherConnectedRemoteId=i8.prototype.aa;i8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
i8.prototype.getReconnectTimeout=i8.prototype.H;i8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
i8.prototype.getAutoplayMode=i8.prototype.ba;i8.prototype.ga=function(){return this.G||""};
i8.prototype.getAutoplayVideoId=i8.prototype.ga;i8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Du(a.o);a.start()}};
i8.prototype.reconnect=i8.prototype.wa;i8.prototype.ka=function(a,b){o8(this,a,b);DFa(this)};
i8.prototype.sendMessage=i8.prototype.ka;g.C(p8,p7);g.h=p8.prototype;g.h.Ee=function(a){return this.ld.$_gs(a)};
g.h.contains=function(a){return!!this.ld.$_c(a)};
g.h.get=function(a){return this.ld.$_g(a)};
g.h.start=function(){this.ld.$_st()};
g.h.add=function(a,b,c){this.ld.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ld.$_r(a,b,c)};
g.h.Lr=function(a,b,c,d){this.ld.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.A.length;a<b;++a)this.ld.$_ubk(this.A[a]);this.A.length=0;this.ld=null;p8.fa.Y.call(this)};
g.h.IY=function(){this.V("screenChange")};
g.h.NU=function(){this.V("onlineScreenChange")};
y7.prototype.$_st=y7.prototype.start;y7.prototype.$_gspc=y7.prototype.JY;y7.prototype.$_gsppc=y7.prototype.pH;y7.prototype.$_c=y7.prototype.contains;y7.prototype.$_g=y7.prototype.get;y7.prototype.$_a=y7.prototype.add;y7.prototype.$_un=y7.prototype.Lr;y7.prototype.$_r=y7.prototype.remove;y7.prototype.$_gs=y7.prototype.Ee;y7.prototype.$_gos=y7.prototype.oH;y7.prototype.$_s=y7.prototype.subscribe;y7.prototype.$_ubk=y7.prototype.ce;var q8=null,r8=null,G8=null,v8=[];g.t(H8,g.L);g.h=H8.prototype;
g.h.Y=function(){g.L.prototype.Y.call(this);this.B.stop();this.D.stop();this.K.stop();this.N();this.o.unsubscribe("proxyStateChange",this.PE,this);this.o.unsubscribe("remotePlayerChange",this.Nn,this);this.o.unsubscribe("remoteQueueChange",this.Kq,this);this.o.unsubscribe("autoplayUpNext",this.lE,this);this.o.unsubscribe("previousNextChange",this.ME,this);this.o.unsubscribe("nowAutoplaying",this.DE,this);this.o.unsubscribe("autoplayDismissed",this.kE,this);this.o=this.C=null};
g.h.iD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(K8(this)){if(!c8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":c8(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Lm(c[0],c[1]);break;case "control_subtitles_set_track":L8(this,c[0]);break;case "control_set_audio_track":c=c[0],K8(this)&&this.o.Ux(this.T.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();M8(this,0==c?void 0:c);break;case "control_seek":M8(this,c[0]);break;case "control_subtitles_set_track":L8(this,c[0]);break;case "control_set_audio_track":c=c[0],K8(this)&&this.o.Ux(this.T.getVideoData(1).videoId,c)}};
g.h.JS=function(a){this.K.PL(a)};
g.h.jY=function(a){this.iD("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.xG=function(){var a=this.T.Gc("captions","track");g.Zb(a)||L8(this,a)};
g.h.zE=function(a){if(K8(this)){this.o.unsubscribe("remotePlayerChange",this.Nn,this);var b=Math.round(a.volume);a=!!a.muted;var c=c8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.Nn,this)}};
g.h.iU=function(){g.Zb(this.F)||YFa(this,this.F);this.G=!1};
g.h.PE=function(a,b){this.D.stop();2==b&&this.uG()};
g.h.Nn=function(){if(K8(this)){this.B.stop();var a=c8(this.o);switch(a.o){case 1080:case 1081:case 1084:case 1085:this.C.G=1;break;case 1082:case 1083:this.C.G=0;break;default:this.C.G=-1}switch(a.o){case 1081:case 1:J8(this,new g.NP(8));this.tG();break;case 1085:case 3:J8(this,new g.NP(9));break;case 1083:case 0:J8(this,new g.NP(2));this.J.stop();I8(this,this.T.getVideoData().lengthSeconds);break;case 1084:J8(this,new g.NP(4));break;case 2:J8(this,new g.NP(4));I8(this,Y7(a));break;case -1:J8(this,
new g.NP(64));break;case -1E3:J8(this,new g.NP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=c8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,YFa(this,a));a=c8(this.o);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.XG()}else XFa(this)};
g.h.ME=function(){this.T.V("mdxpreviousnextchange")};
g.h.Kq=function(){K8(this)||XFa(this)};
g.h.TK=function(){this.o.kA()};
g.h.lE=function(a){a&&(a=g.HE("/watch_queue_ajax",{method:"GET",fd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.tW,this)}))&&(this.N=(0,g.B)(a.abort,a))};
g.h.tW=function(a,b){var c=new g.$O(g.X(this.T),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.DE=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.kE=function(){this.T.V("mdxautoplaycanceled")};
g.h.NQ=function(a,b){-1==c8(this.o).o?M8(this,a):b&&this.o.mH(a)};
g.h.XG=function(){if(K8(this)){var a=c8(this.o);this.A.Ha(this.O);a.muted?this.T.mute():this.T.vg();this.T.setVolume(a.volume);this.O=this.A.R(this.T,"onVolumeChange",this.zE)}};
g.h.tG=function(){this.B.stop();if(!this.o.la()){var a=c8(this.o);a.sb()&&J8(this,new g.NP(8));I8(this,Y7(a));this.B.start()}};
g.h.uG=function(){this.D.stop();this.B.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(N8,g.V);N8.prototype.D=function(a){$Fa(this,a.state)};g.t(O8,g.yY);O8.prototype.K=function(){var a=this.T.Gc("remote","receivers");a&&1<a.length&&!this.T.Gc("remote","quickCast")?(this.H=g.jb(a,this.D,this),g.zY(this,(0,g.I)(a,this.D)),a=this.T.Gc("remote","currentReceiver"),this.Jf(this.D(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.D=function(a){return a.key};
O8.prototype.If=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
O8.prototype.Ed=function(a){g.yY.prototype.Ed.call(this,a);this.T.Xd("remote","currentReceiver",this.H[a]);this.C.Qb()};g.t(P8,g.BU);g.h=P8.prototype;g.h.create=function(){RFa(g.bN(g.X(this.player)));this.D.push(g.jG("yt-remote-before-disconnect",this.FS,this));this.D.push(g.jG("yt-remote-connection-change",this.xV,this));this.D.push(g.jG("yt-remote-receiver-availability-change",this.NE,this));this.D.push(g.jG("yt-remote-auto-connect",this.vV,this));this.D.push(g.jG("yt-remote-receiver-resumed",this.uV,this));this.NE()};
g.h.load=function(){this.player.Cv();g.BU.prototype.load.call(this);this.C=new H8(this,this.player,this.o);var a=(a=WFa())?a.currentTime:0;var b=F8()?new b8(A8(),void 0):null;0==a&&b&&(a=Y7(c8(b)));0!=a&&(this.J=a||0,this.player.V("progresssync",a,void 0));ZFa(this,this.F,this.F);g.M_(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.of(this.C,this.o);this.o=this.C=null;g.BU.prototype.unload.call(this);g.M_(this.player.app,5)};
g.h.Y=function(){g.kG(this.D);g.BU.prototype.Y.call(this)};
g.h.Bn=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.iD.apply(this.C,[a].concat(g.fa(c)))};
g.h.KL=function(){return this.loaded?this.C.suggestion:null};
g.h.mg=function(){return this.o?c8(this.o).mg:!1};
g.h.hasNext=function(){return this.o?c8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.BQ=function(){var a=c8(this.o),b=this.player.getVideoData();return{allowSeeking:g.X(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Zc():!a.isAdPlaying()&&this.player.Zc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+W7(a):a.C,isPeggedToLive:1>=(a.F?a.B+W7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+W7(a):a.B,seekableStart:0<a.D?a.D+W7(a):a.D}};
g.h.CQ=function(){this.o&&this.o.kH()};
g.h.DQ=function(){this.o&&this.o.lH()};
g.h.FS=function(a){1==a&&(this.K=this.o?c8(this.o):null)};
g.h.xV=function(){var a=F8()?new b8(A8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.mf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.NC(a.videoId,Y7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.NE=function(){this.H=[this.A].concat(TFa());var a=B8()||this.A;Q8(this,a);this.player.za("onMdxReceiversChange")};
g.h.vV=function(){var a=B8();Q8(this,a)};
g.h.uV=function(){this.B=B8()};
g.h.AQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?S7():Q8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&S7(),!0):!1}};
g.h.EQ=function(){g8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ic=function(){return!1};g.zX.remote=P8;})(_yt_player);
